import ExactPageShell from "@/components/ExactPageShell";
import { services } from "@/data/services";
import Link from "next/link";

export default function Services(){return <ExactPageShell>
  <section className="inner-hero"><div className="inner-copy"><p className="inner-kicker">MANAGED TECHNOLOGY SERVICES</p><h1>Technical capability,<br/><span>delivered with discipline.</span></h1><p>Flexible project and managed-service support for organisations that need secure, dependable and scalable technology operations.</p><div className="inner-actions"><Link className="inner-primary" href="/contact">Discuss your requirements ↗</Link><Link className="inner-secondary" href="/solutions">View solution packages</Link></div></div><div className="service-radar"><div className="radar-ring r1"/><div className="radar-ring r2"/><div className="radar-ring r3"/><div className="radar-core">W</div></div></section>
  <section className="inner-content"><div className="section-heading-row"><div><p className="inner-section-kicker">CORE CAPABILITIES</p><h2>Services designed around business continuity and growth</h2></div><p>Open any service to review its benefits, deliverables, technologies and suitable industries.</p></div><div className="inner-service-grid">{services.map((service,i)=><article className="inner-card service-card" key={service.slug}><span className="service-number">{String(i+1).padStart(2,"0")}</span><h3>{service.name}</h3><p>{service.short}</p><Link className="learn-more-link" href={`/services/${service.slug}`}>Learn more <span>↗</span></Link></article>)}</div>
  <div className="process-band"><div><span>01</span><b>Assess</b><p>Understand the environment, risks and priorities.</p></div><div><span>02</span><b>Design</b><p>Define a practical solution and delivery plan.</p></div><div><span>03</span><b>Implement</b><p>Deploy carefully with clear communication.</p></div><div><span>04</span><b>Support</b><p>Monitor, improve and document the outcome.</p></div></div></section>
</ExactPageShell>}
