import ExactPageShell from "@/components/ExactPageShell";
import Link from "next/link";
const solutions=[
["Essential IT Care","A practical support foundation for small teams requiring reliable remote assistance and system upkeep.",["Remote help desk","Endpoint checks","Microsoft 365 administration","Monthly service review"]],
["Secure Business Operations","A security-led package for organisations that need stronger access, visibility and resilience.",["Security baseline review","Identity and email protection","Backup and recovery review","Awareness guidance"]],
["Connected Workforce","A structured solution for distributed teams, branches and remote operations.",["VPN and secure access","Wi-Fi and network management","Cloud collaboration","Connectivity failover"]],
["Automation & Growth","Workflow and platform improvements that reduce manual administration and support revenue operations.",["Process discovery","n8n and API automation","Lead routing","Management reporting"]],
];
export default function Solutions(){return <ExactPageShell><section className="inner-hero"><div className="inner-copy"><p className="inner-kicker">SOLUTION PACKAGES</p><h1>Structured services for<br/><span>specific business outcomes.</span></h1><p>Choose a clear starting point, then tailor the scope to your organisation, risk profile and operational priorities.</p><div className="inner-actions"><Link className="inner-primary" href="/contact">Request a tailored proposal ↗</Link></div></div><div className="contact-orbit"><div className="orbit-dot d1"/><div className="orbit-dot d2"/><div className="orbit-dot d3"/><span>SECURE<br/>SCALE</span></div></section><section className="inner-content"><div className="section-heading-row"><div><p className="inner-section-kicker">ENGAGEMENT OPTIONS</p><h2>Professional packages with room to adapt</h2></div><p>Final scope and pricing are confirmed after a short discovery consultation.</p></div><div className="solution-grid">{solutions.map(([title,desc,features])=><article className="solution-card" key={title as string}><span className="solution-tag">BUSINESS SOLUTION</span><h3>{title as string}</h3><p>{desc as string}</p><ul>{(features as string[]).map(f=><li key={f}>{f}</li>)}</ul><Link href="/contact">Discuss this solution ↗</Link></article>)}</div></section></ExactPageShell>}
